services:
  postgres:
    image: postgres:13
    ports:
      - '15432:5432'
    restart: always
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'develop'
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis:latest
    ports:
      - '16379:6379'
    restart: always

  rocketmq-broker:
    image: apache/rocketmq:5.3.1
    user: root
    # restart: always
    # container_name: rocketmq-broker
    volumes:
      # 映射本地目录权限一定要设置为 777 权限，否则启动不成功
      - ./docker-data/rocketmq/broker_logs:/home/rocketmq/logs
      - ./docker-data/rocketmq/broker_data:/home/rocketmq/store
      - ./conf/broker.conf:/home/rocketmq-5.3.1/conf/broker.conf
      # - ./conf:/home/rocketmq-5.3.1/conf
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
      # - JAVA_OPTS:=-Duser.home=/opt
      - JAVA_OPT_EXT=-server -Xms64m -Xmx64m -Xmn64m
    depends_on:
      - rocketmq-namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    command: sh mqbroker -c /home/rocketmq-5.3.1/conf/broker.conf

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.1
    restart: always
    # container_name: rocketmq-namesrv
      # environment:
      #   JAVA_OPT_EXT: "-server -Xms64m -Xmx64m -Xmn64m"
    volumes:
      # 映射本地目录权限一定要设置为 777 权限，否则启动不成功
      - ./docker-data/rocketmq/namesrv_logs:/home/rocketmq/logs
    ports:
      - 9876:9876
    command: sh mqnamesrv
  rmqdashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    restart: always
    # container_name: rocketmq-dashboard
    environment:
      - JAVA_OPTS=-Drocketmq.config.namesrvAddr=rocketmq-namesrv:9876 -Dserver.port=8180 -Drocketmq.config.isVIPChannel=false
      # - JAVA_OPT_EXT=-Xms128m -Xmx128m -Xmn128m
    depends_on:
      - rocketmq-namesrv
    ports:
      - 8180:8180

## 使用本地目录作为数据卷挂载，路径位于项目根 `docker-data/` 子目录下
