definitions:
  controllers.DespoitRequest:
    properties:
      amount:
        type: number
      symbol:
        type: string
      user_id:
        type: string
    type: object
  controllers.LoginRequest:
    properties:
      captcha:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.OrderCreateRequest:
    properties:
      amount:
        type: number
      order_type:
        allOf:
        - $ref: '#/definitions/github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderType'
        example: limit
      price:
        example: 1
        type: number
      qty:
        example: 12
        type: number
      side:
        allOf:
        - $ref: '#/definitions/github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderSide'
        example: buy
      symbol:
        example: btcusdt
        type: string
    required:
    - order_type
    - side
    - symbol
    type: object
  controllers.RegisterRequest:
    properties:
      captcha:
        type: string
      email:
        type: string
      password:
        type: string
      repeat_password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - repeat_password
    - username
    type: object
  controllers.TransferRequest:
    properties:
      amount:
        type: number
      from:
        type: string
      symbol:
        type: string
      to:
        type: string
    type: object
  controllers.WithdrawRequest:
    properties:
      amount:
        type: number
      symbol:
        type: string
      user_id:
        type: string
    type: object
  github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderSide:
    enum:
    - bid
    - ask
    type: string
    x-enum-varnames:
    - OrderSideBuy
    - OrderSideSell
  github_com_yzimhao_trading_engine_v2_pkg_matching_types.OrderType:
    enum:
    - limit
    - market
    - marketQty
    - marketAmount
    type: string
    x-enum-varnames:
    - OrderTypeLimit
    - OrderTypeMarket
    - OrderTypeMarketQuantity
    - OrderTypeMarketAmount
info:
  contact: {}
paths:
  /api/v1/asset/{symbol}/history:
    get:
      consumes:
      - application/json
      description: get an asset history
      operationId: v1.asset.history
      parameters:
      - description: symbol
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: get asset history
      tags:
      - asset
  /api/v1/asset/despoit:
    post:
      consumes:
      - application/json
      description: despoit an asset
      operationId: v1.asset.despoit
      parameters:
      - description: despoit request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.DespoitRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: asset despoit
      tags:
      - asset
  /api/v1/asset/transfer/{symbol}:
    post:
      consumes:
      - application/json
      description: transfer an asset
      operationId: v1.asset.transfer
      parameters:
      - description: symbol
        in: path
        name: symbol
        required: true
        type: string
      - description: transfer request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.TransferRequest'
      produces:
      - application/json
      responses: {}
      summary: asset transfer
      tags:
      - asset
  /api/v1/asset/withdraw:
    post:
      consumes:
      - application/json
      description: withdraw an asset
      operationId: v1.asset.withdraw
      parameters:
      - description: withdraw request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controllers.WithdrawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: asset withdraw
      tags:
      - asset
  /api/v1/base/exchange_info:
    get:
      consumes:
      - application/json
      description: get exchange info
      operationId: v1.base.exchange_info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: exchange info
      tags:
      - base
  /api/v1/market/depth:
    get:
      consumes:
      - application/json
      description: get depth
      operationId: v1.market.depth
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: depth
      tags:
      - market
  /api/v1/market/klines:
    get:
      consumes:
      - application/json
      description: 获取K线数据
      operationId: v1.market.klines
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: period
        enum:
        - M1
        - M3
        - M5
        - M15
        - M30
        - H1
        - H2
        - H4
        - H6
        - H8
        - H12
        - D1
        - D3
        - W1
        - MN
        in: query
        name: period
        type: string
      - description: start
        in: query
        name: start
        type: integer
      - description: end
        in: query
        name: end
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: klines
      tags:
      - market
  /api/v1/market/trades:
    get:
      consumes:
      - application/json
      description: 获取近期成交记录
      operationId: v1.market.trades
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: trades
      tags:
      - market
  /api/v1/order/create:
    post:
      consumes:
      - application/json
      description: create order
      operationId: v1.order.create
      parameters:
      - description: args
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/controllers.OrderCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: create order
      tags:
      - order
  /api/v1/order/history:
    get:
      consumes:
      - application/json
      description: history list
      operationId: v1.order.history
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: start
        in: query
        name: start
        required: true
        type: integer
      - description: end
        in: query
        name: end
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: history list
      tags:
      - order
  /api/v1/order/trade/history:
    get:
      consumes:
      - application/json
      description: trade history list
      operationId: v1.order.trade_history
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: trade history list
      tags:
      - order
  /api/v1/order/unfinished:
    get:
      consumes:
      - application/json
      description: unfinished list
      operationId: v1.order.unfinished
      parameters:
      - description: symbol
        in: query
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: unfinished list
      tags:
      - order
  /api/v1/ping:
    get:
      description: test if the server is running
      operationId: v1.ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - base
  /api/v1/product:
    get:
      consumes:
      - application/json
      description: get product list
      operationId: v1.product.list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: product list
      tags:
      - product
  /api/v1/product/:symbol:
    get:
      consumes:
      - application/json
      description: get product detail
      operationId: v1.product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: product detail
      tags:
      - product
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: user login
      operationId: v1.user.login
      parameters:
      - description: args
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user login
      tags:
      - user
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: user register
      operationId: v1.user.register
      parameters:
      - description: args
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: user register
      tags:
      - user
  /api/v1/version:
    get:
      consumes:
      - application/json
      description: 程序版本号和编译相关信息
      operationId: v1.version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: version
      tags:
      - base
swagger: "2.0"
